export { default as NewStudy } from './NewStudy/NewStudy';
export { default as Payment } from './Payment/Payment';
export { default as FirstPayment } from './Payment/FirstPayment';
export { default as PaymentComplete } from './Payment/PaymentComplete';
export { default as StudyDetail } from './StudyDetail/StudyDetail';
export { default as UpdateMyPage } from './UpdateMyPage/UpdateMyPage';
export { default as Home } from './Home/Home';
export { default as MyPage } from './MyPage/MyPage';
export { default as NotFound } from './NotFound/NotFound';
